
### Login Request
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "name": "Robert Oppenheimer",
  "email": "r.oppenheimer@aupp.com",
  "password": "password",
  "role": "instructor"
}

### Login Request
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "name": "Robert Oppenheimer",
  "email": "r.oppenheimer@aupp.com",
  "password": "password",
  "role": "instructor"
}


###
POST http://localhost:5001/auth/login
Content-Type: application/json

{
"email": "phearaneron.soeung@gmail.com",
"password": "?VRb%j'2E5Eu8]~",
"role": "student"
}

### Create Assignment (with Authorization)
POST http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New Assignment Title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

This is a sample assignment description.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="attachment_1"; filename="assignment_material.pdf"
Content-Type: application/pdf

@C:/path_to_file/assignment_material.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get All Assignments for a Course
GET http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments

### Get Assignment Details
GET http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments/683d599fa58ef1a5d7feba6c

### PUBLISH ASSIGMENT
POST http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments/683d599fa58ef1a5d7feba6c/publish?action=publish


### Submit Assignment (with File Upload)
POST http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments/683d599fa58ef1a5d7feba6c/submit
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

This is my submission for the assignment.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="submission_file.pdf"
Content-Type: application/pdf

@/Users/nicksng/Desktop/AUPP-eCampus/backend/requirements.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Assignment
PUT http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments/682f4e98293ab1d6fee28d55
Authorization: Bearer {{your_jwt_token}}
Content-Type: application/json

{
  "title": "Updated Assignment Title",
  "description": "Updated assignment description.",
  "max_file_size": 10485760,
  "max_files": 5
}

### Delete Assignment
DELETE http://localhost:5001/course/682e0f0b5357be2fb67182c9/assignments/682f4e98293ab1d6fee28d55
Authorization: Bearer {{your_jwt_token}}
