### Login Request
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "name": "Robert Oppenheimer",
  "email": "r.oppenheimer@aupp.com",
  "password": "password",
  "role": "instructor"
}

###
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "email": "phearaneron.soeung@gmail.com",
  "password": "?VRb%j'2E5Eu8]~",
  "role": "student"
}