### Login Request
POST http://localhost:5001/auth/login
Content-Type: application/json

{
  "name": "Robert Oppenheimer",
  "email": "r.oppenheimer@aupp.com",
  "password": "password",
  "role": "instructor"
}

###
POST https://irrelevant-bonnibelle-aupp-6d0e6d6c.koyeb.app//auth/login
Content-Type: application/json

{
  "email": "phearaneron.soeung@gmail.com",
  "password": "?VRb%j'2E5Eu8]~",
  "role": "student"
}

###
GET https://irrelevant-bonnibelle-aupp-6d0e6d6c.koyeb.app/users/682d741ed0bd8de4d915e097
