### Get User Profile
# GET /users/{user_id}
GET {{BASE_URL}}/users/{{STUDENT_USER_ID}}
Accept: application/json

###

### Update User Profile
# PUT /users/{user_id}
PUT {{BASE_URL}}/users/{{STUDENT_USER_ID}}
Content-Type: application/json

{
  "name": "Lord Rizzler",
  "email": "phearaneron.soeung@gmail.com"
}

###

### Upload Profile Image (manual boundary)
POST {{BASE_URL}}/users/{{STUDENT_USER_ID}}/upload-image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="photo_2025-06-05_14-37-02.jpg"
Content-Type: image/jpeg

@/Users/phear/Downloads/Telegram Desktop/photo_2025-06-05_14-37-02.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Delete User
# DELETE /users/{user_id}
DELETE {{BASE_URL}}/users/{{USER_ID}}
Authorization: Bearer {{TOKEN}}

###

### Get All Users (admin only)
# GET /users/all
GET {{BASE_URL}}/users/all
Accept: application/json

###

### Search Users
# GET /users/search?q={query}&role={role}
GET {{BASE_URL}}/users/search?q={{QUERY}}&role={{ROLE}}
Authorization: Bearer {{TOKEN}}
Accept: application/json

