services:
  mongo-db:
    image: mongo:5
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data: