services:
  - type: web
    name: flask-app
    runtime: python
    plan: free
    workingDirectory: backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
