name: PR Check for Dev Branch

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build check
        run: npm run build

  koyeb-preview:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://cli.koyeb.com/install.sh | sh

      - name: Deploy Preview to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          koyeb app init preview-${{ github.head_ref }} \
            --git ${{ github.repository }} \
            --branch ${{ github.head_ref }} \
            --type web