name: PR Check for Dev Branch

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./backend
        run: |
          python -m pytest

      - name: Build and test Docker image
        run: |
          docker build -t myapp-backend:test -f backend/Dockerfile .
          docker run --rm myapp-backend:test python -c "import flask; print('Flask installation OK')"

  koyeb-preview:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://cli.koyeb.com/install.sh | sh

      - name: Deploy Preview to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          koyeb app init preview-${{ github.head_ref }} \
            --docker ${{ github.repository }} \
            --branch ${{ github.head_ref }} \
            --ports 5001:http \
            --env FLASK_APP=app.py \
            --env FLASK_RUN_HOST=0.0.0.0 \
            --env FLASK_RUN_PORT=5001