name: Koyeb Deployment

on:
  pull_request:
    branches:
      - dev

jobs:
  koyeb-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          sudo mv /home/runner/.koyeb/bin/koyeb /usr/local/bin/

      - name: Create Koyeb Config File
        run: |
          echo "token: ${{ secrets.KOYEB_API_TOKEN }}" > $HOME/.koyeb.yaml

      - name: Deploy to Koyeb
        run: |
          APP_NAME="9d14690f"
          
          # Deploy to Koyeb
          koyeb service update $APP_NAME \
            --git github.com/${{ github.repository }} \
            --git-branch ${{ github.head_ref }} \
            --ports 5001:http

      - name: Wait for Deployment Status
        run: |
          APP_NAME="9d14690f"
          echo "Waiting for deployment to be ready..."
          MAX_ATTEMPTS=30
          ATTEMPT=0
          
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            STATUS=$(koyeb service get $APP_NAME -o json | jq -r '.status')
          
            if [ "$STATUS" == "READY" ]; then
              echo "Deployment successful!"
              exit 0
            elif [ "$STATUS" == "ERROR" ]; then
              echo "Deployment failed!"
              exit 1
            fi
          
            ATTEMPT=$((ATTEMPT + 1))
            echo "Waiting for deployment... Attempt $ATTEMPT of $MAX_ATTEMPTS"
            sleep 20
          done
          
          echo "Deployment timed out!"
          exit 1