name: Koyeb Deployment Check

on:
  pull_request:
    branches:
      - dev

jobs:
  koyeb-deploy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          sudo mv /home/runner/.koyeb/bin/koyeb /usr/local/bin/

      - name: Create Koyeb Config File
        run: |
          echo "token: ${{ secrets.KOYEB_API_TOKEN }}" > $HOME/.koyeb.yaml

      - name: Test Koyeb Deployment Configuration
        run: |
          APP_NAME=9d14690f
          
          # Test deployment configuration
          koyeb service update $APP_NAME \
            --git github.com/${{ github.repository }} \
            --git-branch ${{ github.head_ref }} \
            --ports 5001:http \

      - name: Verify Service Status
        run: |
          APP_NAME="9d14690f"
          echo "Verifying service status..."
          MAX_ATTEMPTS=3  # Reduced to 3 attempts
          ATTEMPT=0
          
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            STATUS=$(koyeb service get $APP_NAME -o json | jq -r '.status')
          
            if [ "$STATUS" == "READY" ]; then
              echo "Service configuration check successful!"
              exit 0
            elif [ "$STATUS" == "ERROR" ]; then
              echo "Service configuration check failed!"
              exit 1
            fi
          
            ATTEMPT=$((ATTEMPT + 1))
            echo "Checking service... Attempt $ATTEMPT of $MAX_ATTEMPTS"
            sleep 10  # Reduced sleep time to 10 seconds
          done
          
          echo "Service check timed out!"
          exit 1