name: PR Check for Dev Branch

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Run linting
        working-directory: ./backend
        run: flake8 . --max-line-length=120

      - name: Run tests
        working-directory: ./backend
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  koyeb-preview:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          sudo mv ./koyeb /usr/local/bin/

      - name: Login to Koyeb
        run: koyeb login -t ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy Preview
        run: |
          BRANCH_NAME=$(echo ${{ github.head_ref }} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
          koyeb service create $BRANCH_NAME-preview \
            --docker ${{ github.repository }}:${{ github.sha }} \
            --ports 5001:http \
            --routes /$BRANCH_NAME-preview:5001 \
            --env FLASK_APP=app.py \
            --env FLASK_RUN_HOST=0.0.0.0 \
            --env FLASK_RUN_PORT=5001